FROM alpine:3.10.3
RUN apk add --update --no-cache gettext

COPY ./caddytemplates/Caddyfile-saml /caddyfiletemplates/Caddyfile-saml

ENV SAML_CLIENT_LOGLEVEL info

VOLUME /configs

ENTRYPOINT envsubst < ${TEMPLATE_FILE} > ${CADDYFILE}
