{{- if .Values.docDeployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kitcaddy.fullname" . }}-documentation
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "documentation.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.docReplicaCount }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "documentation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.docPodAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "documentation.selectorLabels" . | nindent 8 }}
        {{- if .Values.docPodLabels }}
        {{- toYaml .Values.docPodLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "kitcaddy.fullname" . }}-documentation
          securityContext:
            capabilities:
              drop:
                - ALL
              {{- if (.Values.docDeployment.securityContextAddCapabilities) }}
              add:
                {{- toYaml .Values.docDeployment.securityContextAddCapabilities | nindent 16 }}
              {{- end }}
            readOnlyRootFilesystem: {{ .Values.docDeployment.securityContext.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.docDeployment.securityContext.allowPrivilegeEscalation }}
            runAsNonRoot: {{ .Values.docDeployment.securityContext.runAsNonRoot }}
            {{- if (.Values.docDeployment.securityContext.extra) }}
            {{- toYaml .Values.docDeployment.securityContext.extra | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}-documentation:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.docDeployment.env | nindent 12 }}
          ports:
            - name: container-port
              containerPort: {{ .Values.docDeployment.containerPort }}
            {{- range $name, $port := .Values.docDeployment.extraContainerPort }}
            - name: {{ $name }}
              containerPort: {{ $port }}
            {{- end }}
          {{- if (.Values.docDeployment.livenessProbe) }}
          livenessProbe:
            {{- toYaml .Values.docDeployment.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if (.Values.docDeployment.readinessProbe) }}
          readinessProbe:
            {{- toYaml .Values.docDeployment.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.docDeployment.resources | nindent 12 }}
{{- end -}}