apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kitcaddy.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "kitcaddy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
    {{- end }}
  {{- if (.Values.deploymentStrategy) }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kitcaddy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kitcaddy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kitcaddy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - -config
            - /config/config.json
          env: []
          image: "{{ .Values.kitcaddy.image.repository }}:{{ .Values.kitcaddy.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
              name: proxy-port
            {{- range $key, $value := .Values.kitcaddy.extraPorts }}
            - containerPort: {{ $value }}
              name: {{ $key }}
            {{- end }}
          resources:
            {{- toYaml .Values.kitcaddy.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: caddy-config
            {{- range $key, $value := .Values.kitcaddy.extraVolumeMounts }}
            - mountPath: {{ $value.mountPath}}
              name: {{ $key }}
            {{- end }}

      {{- if .Values.deployment.enabled }}
        - name: {{ include "kitcaddy.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: {{ if (not .Values.deployment.env) }}[]{{ end }}

            {{- range $key, $value := .Values.deployment.env }}
            - name: {{ $key }}
            {{- if (not $value.type) }}
              value: {{ $value.value | quote }}
            {{- else if eq $value.type "fieldPath" }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $value.value }}
            {{- else if eq $value.type "secretKeyRef" }}
              valueFrom:
                secretKeyRef:
                  key: {{ $value.key }}
                  name: {{ $value.name }}
            {{- end }}
            {{- end }}
          ports:
            - name: container-port
              containerPort: {{ .Values.deployment.containerPort }}

          {{- if or (.Values.deployment.configMapMountPath) (.Values.deployment.extraVolumeMounts) }}
          volumeMounts:
          {{- end }}
          {{- if (.Values.deployment.configMapMountPath) }}
            - mountPath: {{ .Values.deployment.configMapMountPath }}
              name: caddy-config
          {{- end }}
          {{- range $key, $value := .Values.deployment.extraVolumeMounts }}
            - mountPath: {{ $value.mountPath }}
              name: {{ $key }}
          {{- end }}

          {{- if (.Values.deployment.livenessProbe) }}
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{- end }}

          {{- if (.Values.deployment.readinessProbe) }}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- end }}

      volumes:
        - configMap:
            name: {{ include "kitcaddy.fullname" . }}-config
          name: caddy-config
        {{- range $key, $value := .Values.kitcaddy.extraVolumes }}
        - name: {{$key}}
          {{- tpl . $ | nindent 10 -}}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
