apiVersion: v1
kind: Service
metadata:
  name: {{ include "kitcaddy.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "kitcaddy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- range $key, $value := .Values.service.extraPorts }}
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol | default "TCP" }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "kitcaddy.selectorLabels" . | nindent 4 }}
