{{- if .Values.netpol.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kitcaddy.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      {{- include "kitcaddy.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 80 #KitCaddy default
          protocol: TCP
        {{- range $key, $value := .Values.kitcaddy.extraPorts }}
        - port: {{ $value }}
          protocol: TCP
        {{- end }}

{{- end }}