{{- range $name, $value := .Values.sealedSecret}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ $name }}
  namespace: {{ $.Values.namespace | default "default" }}
spec:
  encryptedData:
    {{- range $key, $secrect := $value.encryptedData}}
    {{ $key }}: {{ $secrect }}
    {{- end }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ $name }}
      namespace: {{ $.Values.namespace | default "default" }}
    type: {{ $value.type | default "Opaque" }}
---
{{- end }}